### ISSUE TITLE
TOC broken where there's no headings, include all text

### ISSUE THREAD

**Issue by mikelmaron** [osmfoundation/welcome-mat#3]

**Comment by tyrasd** [comment]
I believe this is because of the usage of a [custom jekyll plugin](https://github.com/osmfoundation/welcome-mat/blob/gh-pages/_plugins/toc.rb) to generate the table of content side-bar, which isn't supported on github pages. See https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/ :

> Other plugins are not supported, so the only way to incorporate them in your site is to generate your site locally and then push your site's static files to your GitHub Pages site.

**Comment by tyrasd** [comment]
see #9 for a possible solution for this
